### ISSUE TITLE
Cannot run train_crf.lua

### ISSUE THREAD

**Issue by sunyanfred** [zihangdai/CFO#2]
After pre-processing, I have encountered a problem when I am trying to run train_crf.lua.

The feedback in the system is:

/home/sy/torch/install/bin/luajit: /home/sy/virtuoso-opensource/src/model/CRF.lua:192: invalid arguments: DoubleTensor number DoubleTensor 
expected arguments: [*DoubleTensor*] DoubleTensor index LongTensor
stack traceback:
	[C]: in function 'gather'
	/home/sy/virtuoso-opensource/src/model/CRF.lua:192: in function 'forward'
	train_crf.lua:130: in main chunk
	[C]: in function 'dofile'
	...e/sy/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x004064f0

Could you please help me figure it out?

**Comment by wudapeng268** [comment]
Hi sunyanfred, 
When I run pre-processing, I got the error like this:
`module' object has no attribute 'id_query_str`
accurately the module is `virtuoso` so my question is how install virtuoso in python for you ? my virtuoso version is 0.12.6, what's yours? I also install SQLAlchemy (0.6.0) pyodbc(4.0.6) and rdflib (5.0.0.dev0).
I will appreciate it if you can give me any suggestion!

**Comment by zihangdai** [comment]
Fixed for now.
